### ISSUE TITLE
Code Todo-Backend example

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#166]
This could be a perfect task to start working on the project. If you would like to get involved or just play with a different toolkit for HTTP services, keep reading!

To get familiar with the project and set things up, you should read the [contributing](https://github.com/hexagonkt/hexagon/blob/master/contributing.md) document first. If something is not clear or doesn't work right, don't worry and post a comment, I will help you with that (and fix the document for the next one :wink:).

Your task, should you choose to accept it, would be to code an small example following the [guidelines](http://www.todobackend.com).

This exercise will give you a grasp on the project to further propose or develop improvements (if you are willing to continue committing code).

To complete this task:

- [ ] Fork the [sample project](https://github.com/hexagonkt/todo_backend)
- [ ] Code the service following [these indications](http://www.todobackend.com/contribute.html)
- [ ] Deploy the project to an online server using [Travis CI](https://travis-ci.org/)
- [ ] Check that it complies with Todo-Backend automated tests
- [ ] Create a Pull Request to https://github.com/hexagonkt/todo_backend from your fork
- [ ] And lastly create another PR to Todo-Backend's GitHub repository to list your implementation there (you get two contributions for the price of one :wink:)
- [ ] As an optional addition, you can add [Codecov](https://codecov.io) test coverage report inside the Travis CI pipeline

For reference, you can check this other example (more complex, but with the same scope): https://github.com/hexagonkt/real_world

This is a long task, but you will develop a whole service from coding to deploying automatically using continuous integration. And of course, I will help you with it if you ask me (as I already did developments like this).

Have fun, and happy coding!

**Comment by DennisHartrampf** [comment]
I'd like to give this one a try! Happy #hacktoberfest :)

**Comment by DennisHartrampf** [comment]
Hi @jaguililla,

I'm having difficulties getting the application running on Heroku, because the embedded Jetty server binds to the default port 2010 instead of the port Heroku wants it to bind to. The port Heroku wants the server to use is stored in an environment variable `PORT`.

According to https://hexagonkt.com/hexagon_core/#settings I tried putting the port into

1. An environment variable `SERVICE_BINDPORT` (1235)
1. An environment variable `SERVICE_bindPort` (1236)
1. A file `service.yaml` in the root directory of the application with the content `bindPort : 1234`

Still the server binds to default port 2010. Please see attached log output. From what I understant from the documentation, the `service.yaml` file setting (port 1234) should win.

```
16:08:13.965 INFO  [main              ] c.h.settings.SettingsManager   | Settings loaded from Resource with path: service.yaml:

    serviceName: "Todo"
    serviceUrl: "http://hexagonkt.com"
    serviceDescription: "The atoms of your platform"
    serviceLongDescription: "Hexagon is a microservices library written in Kotlin. Its\
      \ purpose is to ease the building of services (Web applications, APIs or queue consumers)\
      \ that run inside a cloud platform\n"
    cdn: "http://cdnjs.cloudflare.com/ajax/libs"
    bootstrapVersion: "3.3.7"
    authorName: "Juanjo Aguililla"
    httpKeywords: "Hexagon, Kotlin, Example, MongoDB, JVM, Web"
    httpGenerator: "Hexagon"
    themeColor: "#135AA1"
    twitterAccount: "@hexagon_kt"
    bindPort: 2010
    bindAddress: "0.0.0.0"
    database: "todo"

16:08:13.965 INFO  [main              ] c.h.settings.SettingsManager   | Settings loaded from Environment Variables starting with: SERVICE_:

    BINDPORT: "1235"
    bindPort: "1236"

16:08:13.965 INFO  [main              ] c.h.settings.SettingsManager   | No settings found for System Properties starting with: service
16:08:13.980 INFO  [main              ] c.h.settings.SettingsManager   | Settings loaded from File with path: C:\Users\dennis.hartrampf\Repositories\kata\todo_backend\service.yaml:

    bindPort: 1234

16:08:13.980 INFO  [main              ] c.h.settings.SettingsManager   | No settings found for Resource with path: service_test.yaml
16:08:14.824 INFO  [main              ] c.hexagonkt.http.server.Server | Todo started

    SERVICE:     Todo
    SERVER TYPE: JettyServletAdapter

    Running in 'nb-ber03-0530' with 4 CPUs 65.536 KB
    Java 1.8 [Java HotSpot(TM) 64-Bit Server VM]
    Locale de_DE.Cp1252 Timezone Europe/Berlin Charset windows-1252

    Started in 1,508 s using 21.204 KB
    Served at http://169.254.55.139:2010
```

As you can see, the application is pickung up both environment variables and the content from the `service.yaml`. But it is not using them to change the bind port.
Can you tell me, what I'm doing wrong here? Do I use the wrong propertie names?

**Comment by jaguililla** [comment]
Sorry to reply this late @DennisHartrampf 

First, thanks for taking the time to check this project and contribute :)

I'm sorry to say that @JohanneA claimed this issue before and I didn't update it in time... my fault.

However, if you want to contribute, you can also pick #211 or #212 which are other cool examples. Or maybe you two can team up to complete the issue :)

I reviewed your problem, and I tried to change the port in the configuration file and it picked the change. Check that you've got the latest Hexagon dependency, if the problem persist I'll dig out a bit more.

Sorry for the misunderstanding with the task, and I'll be glad to help you if you decide to pick another one or continue with Johanne :)

**Comment by JohanneA** [comment]
Sorry, I didn't realize you had picked this one up too @DennisHartrampf, let me know if you want to work together 😊

**Comment by DennisHartrampf** [comment]
Ah, that's a pity, because I'm already halfway done with the task.
Thanks for the offer to collaborate on this one @JohanneA. But I don't see how this would work for this issue, because it is rather small.
I think I will finish it nonetheless, just for the fun of it. And if it is fine for you @jaguililla create a PR on @TodoBackend when I'm done. And afterwards I might take a look at #212 ;)

@jaguililla Thanks for the advice on checking the version of the Hexagon dependency! I was using 0.26.1... After upgrading to 1.0.16 the environment variable is picked up and used. So I'm able to run on Heroku now :)

**Comment by jaguililla** [comment]
Great, thank you both!
